### ISSUE TITLE
PDD fails in ugly way if puzzle line is followed by another (not puzzle) comment

### ISSUE THREAD

**Issue by pchmielowski** [yegor256/pdd#63]
In my Python file I have:

        # @todo #0 uncomment following
        # self.__cache(stats)

After running `pdd`, it shows:

````
/var/lib/gems/2.3.0/gems/pdd-0.17.3/lib/pdd/source.rb:143:in `rescue in puzzles': ["in /home/piotrek/dsp/code/calculatingSummary.py", #<PDD::Error: Space expected>] (PDD::Error)
        from /var/lib/gems/2.3.0/gems/pdd-0.17.3/lib/pdd/source.rb:141:in `puzzles'
        from /var/lib/gems/2.3.0/gems/pdd-0.17.3/lib/pdd.rb:97:in `block (3 levels) in xml'
        from /var/lib/gems/2.3.0/gems/pdd-0.17.3/lib/pdd.rb:96:in `each'
        from /var/lib/gems/2.3.0/gems/pdd-0.17.3/lib/pdd.rb:96:in `block (2 levels) in xml'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.7.1/lib/nokogiri/xml/builder.rb:391:in `insert'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.7.1/lib/nokogiri/xml/builder.rb:375:in `method_missing'
        from /var/lib/gems/2.3.0/gems/pdd-0.17.3/lib/pdd.rb:95:in `block in xml'
        from /var/lib/gems/2.3.0/gems/nokogiri-1.7.1/lib/nokogiri/xml/builder.rb:293:in `initialize'
        from /var/lib/gems/2.3.0/gems/pdd-0.17.3/lib/pdd.rb:93:in `new'
        from /var/lib/gems/2.3.0/gems/pdd-0.17.3/lib/pdd.rb:93:in `xml'
        from /var/lib/gems/2.3.0/gems/pdd-0.17.3/bin/pdd:90:in `<top (required)>'
        from /usr/local/bin/pdd:23:in `load'
        from /usr/local/bin/pdd:23:in `<main>'
````

After inserting a blank line between these two, everything works fine.
I'm not sure if this is an incorrect behaviour, but for sure the **error message is very poor** - I think it should print at least line number with malformed puzzle.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.5`

**Comment by yegor256** [comment]
@pchmielowski try version 0.17.5 -- the problem is fixed there.

**Comment by yegor256** [comment]
@pchmielowski I'm closing it, the problem is gone, in my opinion. If you see it again, please submit a new ticket. Thanks for using the tool and your contribution!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/pdd#63`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#63` is not in scope.
