### ISSUE TITLE
rule 'IMP' doesn't exist

### ISSUE THREAD

**Issue by yegor256** [yegor256/pdd#66]
```
/app/vendor/bundle/ruby/2.2.0/gems/pdd-0.17.5/lib/pdd.rb:144:in `block in rules': rule 'IMP' doesn't exist (RuntimeError)
	from /app/vendor/bundle/ruby/2.2.0/gems/pdd-0.17.5/lib/pdd.rb:141:in `map'
	from /app/vendor/bundle/ruby/2.2.0/gems/pdd-0.17.5/lib/pdd.rb:141:in `rules'
	from /app/vendor/bundle/ruby/2.2.0/gems/pdd-0.17.5/lib/pdd.rb:92:in `xml'
	from /app/vendor/bundle/ruby/2.2.0/gems/pdd-0.17.5/bin/pdd:63:in `'
	from /app/vendor/bundle/ruby/2.2.0/bin/pdd:23:in `load'
	from /app/vendor/bundle/ruby/2.2.0/bin/pdd:23:in `'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.6`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#66` was not in scope
