### ISSUE TITLE
Unable to run local web version of 0pdd // missing config.yml

### ISSUE THREAD

**Issue by kalloc** [yegor256/pdd#78]
I don't found example config.yml in repo, so if it possible, can you show me an example?

```
0pdd@sz1:~/0pdd$ foreman start -p 8080
17:48:51 web.1  | started with pid 500
17:48:54 web.1  | bundler: failed to load command: rackup (/opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/bin/rackup)
17:48:54 web.1  | Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/0pdd/0pdd/config.yml                         
17:48:54 web.1  |   /opt/0pdd/0pdd/0pdd.rb:80:in `initialize'
17:48:54 web.1  |   /opt/0pdd/0pdd/0pdd.rb:80:in `open'
17:48:54 web.1  |   /opt/0pdd/0pdd/0pdd.rb:80:in `block in <top (required)>'                                                
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1423:in `configure'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1923:in `block (2 levels) in delegate'                                                 
17:48:54 web.1  |   /opt/0pdd/0pdd/0pdd.rb:59:in `<top (required)>'
17:48:54 web.1  |   /opt/0pdd/0pdd/config.ru:21:in `require'
17:48:54 web.1  |   /opt/0pdd/0pdd/config.ru:21:in `block in <main>'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
17:48:54 web.1  |   /opt/0pdd/0pdd/config.ru:in `new'
17:48:54 web.1  |   /opt/0pdd/0pdd/config.ru:in `<main>'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:283:in `start'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/server.rb:148:in `start'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/bin/rackup:4:in `<top (required)>'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/bin/rackup:22:in `load'
17:48:54 web.1  |   /opt/0pdd/0pdd/vendor/bundle/ruby/2.3.0/bin/rackup:22:in `<top (required)>'
17:48:54 web.1  | exited with code 1
17:48:54 system | sending SIGTERM to all processes
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@kalloc can you please submit this ticket to this repository: https://github.com/yegor256/0pdd
